general {
    ignore_empty_input = true
}

background {
    monitor = desc:Dell Inc. DELL U2723QE 8SG6H34
    path = ~/Downloads/wallpapers/owl_4-wallpaper-3840x2160.jpg
}

background {
    monitor = desc:BOE 0x08DF
    path = ~/Downloads/wallpapers/owl_4-wallpaper-1920x1080.jpg
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = rgba(216, 222, 233, .75)
    font_size = 80
    font_family = Roboto Black
    position = -20%, 30%
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(216, 222, 233, .75)
    font_size = 30
    font_family = Roboto Black
    position = -20%, 22%
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    # outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    outer_color = rgba(c9c9c9ee)
    check_color=rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    # position = 0, -35%
    position = -20%, -20%
    halign = center
    valign = center
}
